- name: Create private registry
  ansible.builtin.include_tasks: create_registry.yml
  tags: create_registry

- name: Log into registry
  ansible.builtin.include_tasks: login_registry.yml
  tags: login_registry