---
- hosts: servers
  become: true
  gather_facts: yes
  name: install and configure server
  roles:
    # os_hardening
    - { role: os_hardening, become: True, tags: os_hardening }
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1