---
# setup compose dir structure
- name: setup compose dir structure
  file:
    path: "{{ compose_project_dir }}/{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755
  with_items:
  - wordpress
  - wp-db-data
  - nginx
  - logs/nginx
  tags:
    - dir_ops

- name: create docker-compose.yml file
  file:
    path: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: touch
  tags:
    - file_ops

- name: deploy Docker Compose project for (Wordpress/Mysql containers)
  template:
    src: docker-compose.j2
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - deploy_compose

- name: Run docker-compose up
  command: docker compose -f docker-compose.yml up -d
  args:
    chdir: "{{ compose_project_dir }}"
  tags:
    - compose_run

- name: giving some time for project to start-up
  pause:
    seconds: 10