---
- name: Create wordpress compose directory
  file:
    path: ./wordpress
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy wordpress and mysql compose file
  template:
    src: docker-compose.j2
    dest: "./wordpress/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: Docker Compose up
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: ./wordpress/

- name: giving some time for project to start-up
  pause:
    seconds: 10