---
- name: restart netfilter-persistent
  systemd:
    name: netfilter-persistent
    state: restarted
  notify:
    - restart docker

- name: daemon-reload
  systemd:
    daemon_reload: true

- name: enable docker
  systemd:
    name: docker
    enabled: true

- name: start docker
  systemd:
    name: docker
    state: started

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: delete /var/lib/docker
  file:
    path: /var/lib/docker
    state: absent